### PR TITLE
Add 91 to the list of known ESR version numbers

### PR DESCRIPTION
**Pull request by jcristau**

### CODE REVIEW

**Comment by MihaiTabara** [comment]
Looking at https://github.com/mozilla-releng/shipit/blob/main/api/requirements/public.txt#L77 I assume we'll have to rollout another version of this repo in https://pypi.org/project/mozilla-version/. @jcristau if you wanted to roll that out yourself, I can work around the permissions. If not, one of us can roll that out for now 👍

**Comment by MihaiTabara** [comment]
Filed https://github.com/mozilla-releng/mozilla-version/issues/87 to fix the CI. Force-merging now to unblock this.

**Comment by MihaiTabara** [comment]
@jcristau certainly not blocking since this is a nit as values don't change the logic, but wondering whether it's worth adding an entry for 91 in the following tests to stay consistent?

```
> grep -R '78' * 
gecko.py:    _KNOWN_ESR_MAJOR_NUMBERS = (10, 17, 24, 31, 38, 45, 52, 60, 68, 78, 91)
test/test_gecko.py:    ('68.0esr', 'major_number', '78.0esr'),
test/test_gecko.py:    ('68.0.1esr', 'major_number', '78.0esr'),
test/test_gecko.py:    ('68.1.0esr', 'major_number', '78.0esr'),
test/test_gecko.py:    ('78.0esr', 'major_number'),
test/test_gecko.py:    ('78.0.1esr', 'major_number'),
test/test_gecko.py:    ('78.1.0esr', 'major_number'),
(mozilla-version) 
```

**Comment by jcristau** [comment]
@MihaiTabara we could.  I'm not sure the value, to be honest (i.e. when would the new entry fail but the existing ones not, unless we're specifically removing 91 from the list, which, why would we).

**Pull request merged**
